name: Python CI

on:
  push:
    branches:
      - main  # Runs when code is pushed to the main branch
  pull_request:
    branches:
      - main  # Runs when a pull request is opened for the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu as the environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # This action checks out your code

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Use the version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Upgrade pip to the latest version
        pip install -r requirements.txt  # Install dependencies from your requirements.txt

    - name: Run tests
      run: |
        pytest --maxfail=1 --disable-warnings -q  # Run your tests with pytest
